version: "3.8"

services:
  client:
    image: ghcr.io/futuramafamilyguy/personal-website-client:latest
    environment:
      NODE_ENV: production

  server:
    image: ghcr.io/futuramafamilyguy/personal-website-server:latest
    environment:
      ConnectionStrings__PersonalWebsiteDb: ${PERSONALWEBSITE_CONNECTION_STRING}
      ImageStorageConfiguration__ImageStorageType: ${IMAGE_STORAGE_TYPE}
      ImageStorageConfiguration__BaseImageUrl: ${BASE_IMAGE_URL}
      MarkdownStorageConfiguration__MarkdownStorageType: ${MARKDOWN_STORAGE_TYPE}
      MarkdownStorageConfiguration__BaseUrl: ${BASE_MARKDOWN_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_ACCESS_SECRET}
      AWS_REGION: ${AWS_REGION}
      AmazonS3Configuration__Bucket: ${AMAZONS3_BUCKET}
      BasicAuthConfiguration__AdminUsername: ${ADMIN_USERNAME}
      BasicAuthConfiguration__AdminPassword: ${ADMIN_PASSWORD}
      BasicAuthConfiguration__DisableTrackingUsername: ${DISABLETRACKING_USERNAME}
      BasicAuthConfiguration__DisableTrackingPassword: ${DISABLETRACKING_PASSWORD}
      VisitExclusionConfiguration__ExcludeVisitCookieValue: ${EXCLUDE_VISIT_COOKIE}
      AllowedOrigin: ${ALLOWED_ORIGIN}
      AllowedWwwOrigin: ${ALLOWED_WWW_ORIGIN}
    volumes:
      - wwwroot-data:/app/wwwroot
    restart: unless-stopped

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - "./data:/data/db"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.template:/etc/nginx/conf.d/default.template
    ports:
      - "80:80"
      - "443:443"

volumes:
  wwwroot-data:
