version: "3.8"

services:
  client:
    image: ghcr.io/futuramafamilyguy/personal-website-client:latest
    environment:
      NODE_ENV: production

  server:
    image: ghcr.io/futuramafamilyguy/personal-website-server:latest
    environment:
      ConnectionStrings__PersonalWebsiteDb: ${PERSONALWEBSITE_CONNECTION_STRING}
      ImageStorageConfiguration__ImageStorageType: ${IMAGE_STORAGE_TYPE}
      ImageStorageConfiguration__BaseImageUrl: ${BASE_IMAGE_URL}
      MarkdownStorageConfiguration__MarkdownStorageType: ${MARKDOWN_STORAGE_TYPE}
      MarkdownStorageConfiguration__BaseUrl: ${BASE_MARKDOWN_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_ACCESS_SECRET}
      AWS_REGION: ${AWS_REGION}
      AmazonS3Configuration__Bucket: ${AMAZONS3_BUCKET}
      BasicAuthConfiguration__AdminUsername: ${ADMIN_USERNAME}
      BasicAuthConfiguration__AdminPassword: ${ADMIN_PASSWORD}
      BasicAuthConfiguration__DisableTrackingUsername: ${DISABLETRACKING_USERNAME}
      BasicAuthConfiguration__DisableTrackingPassword: ${DISABLETRACKING_PASSWORD}
      VisitExclusionConfiguration__ExcludeVisitCookieValue: ${EXCLUDE_VISIT_COOKIE}
      AllowedOrigin: ${ALLOWED_ORIGIN}
      AllowedWwwOrigin: ${ALLOWED_WWW_ORIGIN}
    volumes:
      - wwwroot-data:/app/wwwroot
    restart: unless-stopped

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - "./data:/data/db"

  nginx:
    image: nginx:latest
    environment:
      - SERVER_URL=${SERVER_URL}
      - CLIENT_URL=${CLIENT_URL}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./scripts/start-nginx.sh:/start-nginx.sh
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    entrypoint: /bin/sh -c "/start-nginx.sh"
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

volumes:
  wwwroot-data:
