version: "3.8"

services:
  client:
    image: ghcr.io/futuramafamilyguy/personal-website-client:latest
    environment:
      NODE_ENV: production

  server:
    image: ghcr.io/futuramafamilyguy/personal-website-server:latest
    environment:
      ConnectionStrings__PersonalWebsiteDb: ${PERSONALWEBSITE_CONNECTION_STRING}
      ImageStorageConfiguration__Provider: ${IMAGE_STORAGE_PROVIDER}
      ImageStorageConfiguration__Host: ${IMAGE_STORAGE_HOST}
      ImageStorageConfiguration__CdnEnabled: ${CDN_ENABLED_IMAGE_STORAGE}
      MarkdownStorageConfiguration__Provider: ${MARKDOWN_STORAGE_PROVIDER}
      MarkdownStorageConfiguration__Host: ${MARKDOWN_STORAGE_HOST}
      MarkdownStorageConfiguration__CdnEnabled: ${CDN_ENABLED_MARKDOWN_STORAGE}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_ACCESS_SECRET}
      AWS_REGION: ${AWS_REGION}
      AmazonS3Configuration__Bucket: ${AMAZONS3_BUCKET}
      BasicAuthConfiguration__AdminUsername: ${ADMIN_USERNAME}
      BasicAuthConfiguration__AdminPassword: ${ADMIN_PASSWORD}
      BasicAuthConfiguration__DisableTrackingUsername: ${DISABLETRACKING_USERNAME}
      BasicAuthConfiguration__DisableTrackingPassword: ${DISABLETRACKING_PASSWORD}
      VisitExclusionConfiguration__ExcludeVisitCookieValue: ${EXCLUDE_VISIT_COOKIE}
      AllowedOrigin: ${ALLOWED_ORIGIN}
      AllowedWwwOrigin: ${ALLOWED_WWW_ORIGIN}
      CdnConfiguration__HOST: ${CDN_HOST}
    volumes:
      - wwwroot-data:/app/wwwroot
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - "./data:/data/db"

  nginx:
    image: ghcr.io/futuramafamilyguy/personal-website-nginx:latest
    environment:
      - SERVER_URL=http://server:${SERVER_PORT}
      - CLIENT_URL=http://client:${CLIENT_PORT}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      # - allen-cinematic-universe

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

volumes:
  wwwroot-data:

# keeping this in case cross-compose communication is needed again

# networks:
#   allen-cinematic-universe:
#     external: true
