version: "3.8"

services:
  client:
    image: ghcr.io/futuramafamilyguy/personal-website-client:latest
    environment:
      NODE_ENV: production
    depends_on:
      - server
    ports:
      - "127.0.0.1:3000:3000"

  server:
    image: ghcr.io/futuramafamilyguy/personal-website-server:latest
    ports:
      - "127.0.0.1:8443:8080"
    environment:
      ConnectionStrings__PersonalWebsiteDb: ${PERSONALWEBSITE_CONNECTION_STRING}
      FileImageStorageConfiguration__RootImageDirectoryPath: ${IMAGE_DIRECTORY_PATH}
      FileImageStorageConfiguration__BaseImageUrl: ${BASE_IMAGE_URL}
      AmazonS3ImageStorageConfiguration__Bucket: ${AMAZONS3_BUCKET}
      BasicAuthConfiguration__AdminUsername: ${ADMIN_USERNAME}
      BasicAuthConfiguration__AdminPassword: ${ADMIN_PASSWORD}
      BasicAuthConfiguration__DisableTrackingUsername: ${DISABLETRACKING_USERNAME}
      BasicAuthConfiguration__DisableTrackingPassword: ${DISABLETRACKING_PASSWORD}
      VisitExclusionConfiguration__ExcludeVisitCookieValue: ${EXCLUDE_VISIT_COOKIE}
      AllowedOrigin: ${ALLOWED_ORIGIN}
    depends_on:
      - mongo
    volumes:
      - wwwroot-data:/app/wwwroot
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - "./data:/data/db"

volumes:
  wwwroot-data:
