name: deploy docker-compose to vm

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  wait-for-client:
    uses: futuramafamilyguy/personal-website/.github/workflows/release-client.yml@main
    permissions:
      contents: read
      packages: write
    secrets:
      serverUrl: ${{ secrets.VITE_SERVER_URL }}
      sessionUrl: ${{ secrets.VITE_SESSION_URL }}

  wait-for-server:
    uses: futuramafamilyguy/personal-website/.github/workflows/release-server.yml@main
    permissions:
      contents: read
      packages: write

  deploy-to-droplet:
    runs-on: ubuntu-latest
    needs: [wait-for-client, wait-for-server]
    steps:
      - name: checkout docker-ops files
        uses: actions/checkout@v4

      - name: copy docker-ops files to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          source: |
            docker-compose.yml,
            scripts/run-certbot.sh
          target: personal-website

      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          script: |
            cd personal-website
            chmod +x scripts/run-certbot.sh
            docker compose down
            docker image prune -a -f
            docker compose pull
            docker compose up -d
