name: deploy docker-compose to vm

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  check-code-changes:
    runs-on: ubuntu-latest
    outputs:
      server_changed: ${{ steps.filter.outputs.server }}
      client_changed: ${{ steps.filter.outputs.client }}
      nginx_changed: ${{ steps.filter.outputs.nginx }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: check paths for changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - 'server/**'
            client:
              - 'client/**'
            nginx:
              - 'nginx/**'

  wait-for-client:
    needs: check-code-changes
    if: needs.check_changes.outputs.client_changed == 'true'
    uses: futuramafamilyguy/personal-website/.github/workflows/release-client.yml@main
    permissions:
      contents: read
      packages: write
    secrets:
      serverUrl: ${{ secrets.VITE_SERVER_URL }}
      sessionUrl: ${{ secrets.VITE_SESSION_URL }}

  wait-for-server:
    needs: check-code-changes
    if: needs.check_changes.outputs.server_changed == 'true'
    uses: futuramafamilyguy/personal-website/.github/workflows/release-server.yml@main
    permissions:
      contents: read
      packages: write

  wait-for-nginx:
    needs: check-code-changes
    if: needs.check_changes.outputs.nginx_changed == 'true'
    uses: futuramafamilyguy/personal-website/.github/workflows/build-push-nginx.yml@main
    permissions:
      contents: read
      packages: write

  deploy-to-droplet:
    runs-on: ubuntu-latest
    needs: [wait-for-client, wait-for-server, wait-for-nginx]
    steps:
      - name: checkout docker-ops files
        uses: actions/checkout@v4

      - name: copy docker-ops files to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          source: |
            docker-compose.yml,
            scripts/run-certbot.sh
          target: personal-website

      - name: deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          script: |
            cd personal-website
            chmod +x scripts/run-certbot.sh
            docker compose pull
            docker compose up -d
            docker image prune -f
