name: build and deploy .net app to lightsail container

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  SERVICE_NAME: personal-website-server
  AWS_REGION: ap-southeast-2

permissions:
    contents: read
    packages: write
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: run tests
        run: dotnet test server

      - name: log in to container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          push: true
          context: server
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.SERVICE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
      
      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: set up tf
        uses: hashicorp/setup-terraform@v3

      - name: tf init
        run: terraform init
        working-directory: infra

      - name: tf apply
        run: |
          terraform apply -auto-approve \
            -var="image_tag=${{ github.sha }}"
        working-directory: infra
