name: build react client

on:
  workflow_call:
    secrets:
      serverUrl:
        required: true
      sessionUrl:
        required: true
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: personal-website-client

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: log in to container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          push: true
          context: client
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          build-args: |
            VITE_SERVER_URL=${{ secrets.serverUrl }}
            VITE_SESSION_URL=${{ secrets.sessionUrl }}
